..language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'

sudo: false

install:
  - composer install

script:
  - vendor/bin/phpunit --exclude-group createorder

after_success:
    - bash <(curl -s https://codecov.io/bash)